# Generated by Django 5.2.7 on 2025-12-02 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_cart_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
