# Generated by Django 5.2.7 on 2025-12-16 13:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_user_national_id_user_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='SwapRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('offered_listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swap_requests_sent', to='api.listing')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_swaps', to=settings.AUTH_USER_MODEL)),
                ('requested_listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swap_requests_received', to='api.listing')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_swaps', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('requested_listing', 'offered_listing')},
            },
        ),
    ]
