# Generated by Django 5.2.7 on 2025-12-16 20:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_swaprequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='listing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='api.listing'),
        ),
        migrations.AlterUniqueTogether(
            name='conversation',
            unique_together={('listing',)},
        ),
    ]
