# Generated by Django 5.2.7 on 2025-12-16 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_conversation_listing_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='conversation',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='listing',
        ),
    ]
