# Generated by Django 5.2.7 on 2026-01-13 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_order_delivery_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('parent', 'Parent/Guardian'), ('school', 'School Administrator'), ('bookshop', 'Bookshop Owner'), ('rider', 'Rider')], default='parent', max_length=10),
        ),
    ]
