# Generated by Django 5.2.7 on 2026-01-14 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_user_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booklist',
            name='academic_year',
            field=models.CharField(help_text='e.g., 2024-2025', max_length=20),
        ),
    ]
