# Generated by Django 5.2.7 on 2026-01-19 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_remove_delivery_order_delivery_orders_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='current_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='current_lng',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
