# Generated by Django 5.2.7 on 2026-01-27 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_delivery_current_lat_delivery_current_lng_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='delivery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='api.delivery'),
        ),
    ]
