# Generated by Django 5.2.7 on 2026-02-01 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_conversation_delivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('mpesa', 'M-Pesa'), ('card', 'Credit(Paystack)')], default='mpesa', max_length=10),
        ),
        migrations.AddField(
            model_name='payment',
            name='paystack_ref',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
