# Generated by Django 5.2.7 on 2026-02-10 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_delivery_rider'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='textbook',
            name='cover_image',
        ),
        migrations.AddField(
            model_name='textbook',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='listings/'),
        ),
        migrations.AddField(
            model_name='textbook',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='listings/'),
        ),
        migrations.AddField(
            model_name='textbook',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='listings/'),
        ),
    ]
