# Generated by Django 5.2.7 on 2026-02-10 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_remove_textbook_cover_image_textbook_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='textbook',
            name='image',
        ),
        migrations.RemoveField(
            model_name='textbook',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='textbook',
            name='image3',
        ),
        migrations.AddField(
            model_name='listing',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='listings/'),
        ),
        migrations.AddField(
            model_name='listing',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='listings/'),
        ),
        migrations.AddField(
            model_name='listing',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='listings/'),
        ),
        migrations.AddField(
            model_name='textbook',
            name='cover_image',
            field=models.ImageField(blank=True, default='book_covers/default.jpg', null=True, upload_to='book_covers/'),
        ),
    ]
