# Generated by Django 5.2.7 on 2026-02-10 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_remove_textbook_image_remove_textbook_image2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='image',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='image3',
        ),
    ]
